# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.CharField(max_length=100)),
                ('alert_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-alert_time'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.CharField(help_text='Unique device/monitor identifier', max_length=100, primary_key=True, serialize=False)),
                ('timeout', models.PositiveIntegerField(default=60, help_text='Timeout countdown in seconds')),
                ('alert_email', models.EmailField(help_text='Email to notify when the watchdog triggers', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('down', 'Down')], default='active', help_text='Current state of the watchdog monitor', max_length=20)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last received ping')),
                ('next_alert_at', models.DateTimeField(help_text='Calculated timestamp when the monitor will expire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
